# TODO: Computer needs to generate a random number
# TODO: User needs to enter their guessed number until the number generated by computer and entered by the user is matched.

# Importing

import threading

import random

from math import floor

# Play music function coming from another file

from play_music import play_audio, right_sound, wrong_sound


def main():
    while True:
        # Initialize guess count to 0 for tracking attempts
        guess_count = 0

        # Initialize random value to 0
        rand_num = 0
        print("Welcome to the random number guessing game!")

        print("Choose your difficulty level.")

        print("1: Easy - (1-10)")

        print("2: Medium - (1-50)")

        print("3: Hard - (1-100)")

        print("4: Extreme - (1-1000)")

        print(
            "Note: When entered an invalid option, AI will generate a number between 1 to 100 by default."
        )

        difficulty_level = input("What difficulty level you want to choose?\n")

        if difficulty_level == "1":
            rand_num = random.randint(1, 10)

        elif difficulty_level == "2":
            rand_num = random.randint(1, 50)

        elif difficulty_level == "3":
            rand_num = random.randint(1, 100)

        elif difficulty_level == "4":
            rand_num = random.randint(1, 1000)

        else:
            rand_num = floor(random.random() * 100)
            print("Invalid option chosen! AI has chosen a number between 1 to 100!")

        while True:
            try:
                gussed_num = int(input("Enter the guessed number: "))

                if guess_count == 0:
                    guess_count += 1

            except ValueError:
                print("You entered an invalid number. Lets try again!")
                continue

            if gussed_num == rand_num:
                print(f"Yooo! you guessed it right!😊😊 in {guess_count} attempts")
                threading.Thread(target=play_audio, args=(right_sound,)).start()

                play_again = input("Do you want to play again? [y/n]")
                if play_again == "y" or play_again == "Y":
                    break
                else:
                    print("Thanks for playing!😂 Bye👋")
                    exit()

            elif rand_num > gussed_num:
                guess_count += 1
                print(
                    "Number generated by AI is greater than your entered number. Please try again!"
                )
                threading.Thread(target=play_audio, args=(wrong_sound,)).start()
            elif rand_num < gussed_num:
                guess_count += 1
                print(
                    "Number generated by AI is smaller than your entered number. Please try again!"
                )
                threading.Thread(target=play_audio, args=(wrong_sound,)).start()


if __name__ == "__main__":
    main()
